version: "3.9"
services:
  db:
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_PASSWORD: p0stgr3s
      POSTGRES_USER: posts
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U posts"]
      interval: 3s
      timeout: 5s
      retries: 5
  db_ui:
    image: sosedoff/pgweb:0.13.1
    depends_on: 
      db:
        condition: service_healthy
    ports: 
      - "3001:8081" 
    environment:
      - PGWEB_DATABASE_URL=postgresql://posts:p0stgr3s@db:5432/posts?sslmode=disable
  air_api:
    image: cosmtrek/air
    working_dir: /app
    ports:
      - "3000:3000"
    healthcheck:
      test: curl -fsS localhost:3000/health
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy